# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            李哲成
tagline:          'A Jekyll theme'
description:      '这是我的博客'
url:              www.google.com
baseurl:          /

author:
  name:           '李哲成'
  url:            https://www.weibo.com/1146436863/profile?rightmod=1&wvr=6&mod=personinfo

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/BearL222/BearL222.github.io
