# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zhecheng Li
tagline:          'A Jekyll theme'
description:      'This is my blog'
url:              www.google.com
baseurl:          /

author:
  name:           'Zhecheng Li'
  url:            https://www.weibo.com/1146436863/profile?rightmod=1&wvr=6&mod=personinfo

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/BearL222/BearL222.github.io
